* Write a program to read through a file and print the contents of the file (line by line) all in upper case. Executing the program will look as follows:

#+begin_src 
python shout.py
Enter a file name: mbox-short.txt
FROM STEPHEN.MARQUARD@UCT.AC.ZA SAT JAN 5 09:14:16 2008
RETURN-PATH: <POSTMASTER@COLLAB.SAKAIPROJECT.ORG>
RECEIVED: FROM MURDER (MAIL.UMICH.EDU [141.211.14.90])
     BY FRANKENSTEIN.MAIL.UMICH.EDU (CYRUS V2.3.8) WITH LMTPA;
     SAT, 05 JAN 2008 09:14:16 -0500
#+end_src

#+begin_src python
  fname = input("Enter a file name: ")

  try:
      fhandle = open(fname)
  except:
      print(f"File cannot be opened: {fname}")
      exit()

  for line in fhandle:
      print(line.upper(), end="")
#+end_src

* Write a program to prompt for a file name, and then read  through the file and look for lines of the form:

: X-DSPAM-Confidence: 0.8475

When you encounter a line that starts with “X-DSPAM-Confidence:”
pull apart the line to extract the floating-point number on the line. Count these lines and then compute the total of the spam confidence values from these lines. When you reach the end of the file, print out the average spam confidence.

#+begin_src python
  fname = input("Enter a file name: ")

  spam_confidence = 0
  counter = 0

  try:
      fhandle = open(fname)
  except:
      print(f"File cannot be opened: {fname}")
      exit()

  for line in fhandle:
      if line.startswith("X-DSPAM-Confidence:"):
	  colon_pos = line.find(':')
	  number = float(line[colon_pos+1:])
	  spam_confidence += number
	  counter +=  1

  avg_spam_confidence = spam_confidence / counter

  print(f"Average spam confidence: {avg_spam_confidence}")
#+end_src

* Sometimes when programmers get bored or want to have a bit of fun, they add a harmless Easter Egg to their program. Modify the program that prompts the user for the file name so that it prints a funny message when the user types in the exact file name “na na boo boo”. The program should behave normally for all other files which exist and don’t exist.

#+begin_src python
  fname = input("Enter a file name: ")

  if fname == "na na boo boo":
      print("NA NA BOO BOO TO YOU - You have been punk'd!")
      exit()

  try:
      fhandle = open(fname)
  except:
      print(f"File cannot be opened: {fname}")
      exit()
    
  for line in fhandle:
      print(line.upper(), end="")
#+end_src
