* Write a function called chop that takes a list and modifies it, removing the first and last elements, and returns None. Then write a function called middle that takes a list and returns a new list that contains all but the first and last elements.

#+begin_src python
  def chop(l: list):
	l.pop()
	l.pop(0)

  def middle(l):
	return l[1:-1]
#+end_src
* Figure out which line of the program is still not properly guarded. See if you can construct a text file which causes the program to fail and then modify the program so that the line is properly guarded and test it to make sure it handles your new text file.

#+begin_src python
  fhand = open('mbox-short.txt')
  count = 0
  for line in fhand:
      words = line.split()
      # print('Debug:', words)
      if len(words) == 0 : continue
      if words[0] != 'From' : continue
      print(words[2])
#+end_src

Before printing the 3rd element of the ~words~ variable, we should check if there is a 3rd  element:

#+begin_src python
  ...
  if len(words) < 3: continue
  if words[0] != 'From' : continue
#+end_src
* Rewrite the guardian code in the above example without two if statements. Instead, use a compound logical expression using the or logical operator with a single if statement.

#+begin_src python
  if len(words) < 3 or words[0] != "From": continue
#+end_src
